version: '3'

services:
  #api-service:
    #build:
      #context: .
      #dockerfile: Dockerfile  
    #container_name: api-service
    #ports:
      #- "3000:3000"

  web-pos:
    build:
      context: ../sasi-delivery-web
      dockerfile: Dockerfile
    ports:
      - "4000:4000"

  #mysql-service:
    #image: mysql:5.7 
    #container_name: mysql-service
    #restart: always
    #environment:
     # MYSQL_ROOT_PASSWORD: 1234
      #MYSQL_DATABASE: sasirest
     # MYSQL_USER: music
     # MYSQL_PASSWORD: 1234
   #ports:
      #- "3306:3306"
    #volumes:
         # - mysql_data:/var/lib/mysql

#volumes:
  #mysql_data: